name: pr-test

on:
  issue_comment:
    types: [created]
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pr-test:
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest

    steps:

      - name: Check comment command
        uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.event.comment.body }}
          regex: '^/sql-run$'

      - uses: actions/github-script@v3
        id: get-pr
        if: ${{ steps.regex-match.outputs.match != '' }}
        with:
          script: |
            const request = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            }
            core.info(`Getting PR #${request.pull_number} from ${request.owner}/${request.repo}`)
            try {
              const result = await github.pulls.get(request)
              return result.data
            } catch (err) {
              core.setFailed(`Request failed with error ${err}`)
            }

      - name: Check out pull request head
        if: ${{ steps.regex-match.outputs.match != '' }}
        uses: actions/checkout@v2
        with:
          repository: ${{ fromJSON(steps.get-pr.outputs.result).head.repo.full_name }}
          ref: ${{ fromJSON(steps.get-pr.outputs.result).head.sha }}

      - name: Setup node 14 env
        if: ${{ steps.regex-match.outputs.match != '' }}
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Test
        if: ${{ steps.regex-match.outputs.match != '' }}
        env:
          CLICKHOUSE_QUERY_URL: ${{ secrets.CLICKHOUSE_QUERY_URL }}
        run: |
          npm install
          npm run ci

      - name: Update to oss
        if: ${{ steps.regex-match.outputs.match != '' }}
        uses: tvrcgo/upload-to-oss@master
        with:
          key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
          region: ${{ secrets.OSS_REGION }}
          bucket: ${{ secrets.OSS_BUCKET }}
          asset-path: ./dist
          target-path: ${{ secrets.OSS_TARGET_PATH }}

      - id: get-comment-body
        if: ${{ steps.regex-match.outputs.match != '' }}
        run: |
          body=$(cat ./dist/pr-comment.md)
          echo ::set-output name=body::$body

      - name: Create comment
        if: ${{ steps.regex-match.outputs.match != '' }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: ${{ steps.get-comment-body.outputs.body }}
